# CuPy 实验

现在轮到你了。

在这个实验中，我们将练习一些基本的 `cupy` 操作。

开始之前，请关闭 Google Colab 的自动补全功能：点击右上角的设置齿轮 -> Editor -> 取消勾选 "Automatically trigger code completions"。

In [2]:
import cupy as cp

**1. 创建一个包含从 `1` 到 `500_000_000` 的数字的输入数据数组。** 

In [3]:
arr = cp.arange(1, 500_000_000)
arr

array([        1,         2,         3, ..., 499999997, 499999998,
       499999999])

**2. 使用 `nbytes` 计算数组的大小（以 GB 为单位）** _提示：GB 是 `1e9`_

In [4]:
arr.nbytes / 1e9

3.999999992

**3. 数组有多少个维度？**

In [5]:
arr.ndim

1

**4. 数组有多少个元素？**

In [6]:
arr.size

499999999

**5. 数组的形状是什么？**

In [ ]:
arr...

**6. 创建一个包含 `5_000_000` 个元素的新数组，表示从 `0` 到 `1000` 的线性空间。**

In [7]:
arr = cp.linspace(0,1000, num=5_000_000)
arr

array([0.0000000e+00, 2.0000004e-04, 4.0000008e-04, ..., 9.9999960e+02,
       9.9999980e+02, 1.0000000e+03])

**7. 创建一个 `10_000` 行 `5_000` 列的随机数组。**

In [8]:
arr = cp.random.random((10_000, 5_000))
arr

array([[0.02833701, 0.35475449, 0.28679491, ..., 0.00844677, 0.90125257,
        0.9532169 ],
       [0.73597675, 0.35377403, 0.69623355, ..., 0.93166379, 0.62775144,
        0.40315922],
       [0.62218741, 0.77251804, 0.82115688, ..., 0.89906036, 0.09362963,
        0.66827473],
       ...,
       [0.55850375, 0.47536028, 0.68656867, ..., 0.54831803, 0.55480709,
        0.67456728],
       [0.63537607, 0.5119305 , 0.46749032, ..., 0.79646211, 0.13083083,
        0.91546684],
       [0.66735809, 0.33691557, 0.1765687 , ..., 0.06494852, 0.75431403,
        0.83613475]])

**8. 对该数组进行排序。**

In [9]:
arr = cp.sort(arr)
arr

array([[3.13151347e-05, 1.07963832e-04, 2.83484176e-04, ...,
        9.99509397e-01, 9.99554113e-01, 9.99831989e-01],
       [1.02718248e-05, 2.21318875e-05, 6.51118317e-04, ...,
        9.99765053e-01, 9.99966282e-01, 9.99969829e-01],
       [2.56182396e-04, 5.03517069e-04, 6.07921931e-04, ...,
        9.99224422e-01, 9.99256742e-01, 9.99643268e-01],
       ...,
       [1.96848257e-04, 2.65955530e-04, 2.72013643e-04, ...,
        9.98615499e-01, 9.98861533e-01, 9.99693573e-01],
       [1.83276200e-04, 9.06631372e-04, 9.89494894e-04, ...,
        9.99591141e-01, 9.99873180e-01, 9.99925142e-01],
       [1.62085606e-03, 1.74392075e-03, 1.81490304e-03, ...,
        9.99547300e-01, 9.99589242e-01, 9.99747016e-01]])

**附加题 9. 将数组重塑为其中一个维度长度为 `5`**

In [10]:
arr = arr.reshape(10_000, 1_000, 5)
arr

array([[[3.13151347e-05, 1.07963832e-04, 2.83484176e-04, 2.98764904e-04,
         3.73323991e-04],
        [6.66660440e-04, 8.70766173e-04, 1.19174643e-03, 1.60646393e-03,
         1.83752731e-03],
        [2.26550673e-03, 2.30822659e-03, 2.31183360e-03, 2.35428298e-03,
         2.35719781e-03],
        ...,
        [9.96414540e-01, 9.96563669e-01, 9.97010882e-01, 9.97012218e-01,
         9.97098907e-01],
        [9.97258606e-01, 9.97501229e-01, 9.98057299e-01, 9.98220929e-01,
         9.98859413e-01],
        [9.98914846e-01, 9.99482292e-01, 9.99509397e-01, 9.99554113e-01,
         9.99831989e-01]],

       [[1.02718248e-05, 2.21318875e-05, 6.51118317e-04, 6.75587232e-04,
         1.01133533e-03],
        [1.12558906e-03, 1.13041326e-03, 1.63446947e-03, 1.93270111e-03,
         1.95398459e-03],
        [1.99452426e-03, 2.06328455e-03, 2.38577582e-03, 2.55584534e-03,
         3.28557667e-03],
        ...,
        [9.96949800e-01, 9.97230268e-01, 9.97455757e-01, 9.97722969e-01,
        